MAP_2_RMS = ['reward_machines/officeWorld/reward_machines_m2_a1.txt', 'reward_machines/officeWorld/reward_machines_m2_a2.txt']
MAP_2_RMS_DECORATIONS = ['reward_machines/officeWorld/reward_machines_m2_dec_reward_a1.txt', 'reward_machines/officeWorld/reward_machines_m2_dec_reward_a2.txt']
MAP_2_RMS_NOT_0_SUM = ['reward_machines/officeWorld/rm_m2_not_zero_sum_a1.txt', 'reward_machines/officeWorld/rm_m2_not_zero_sum_a2.txt']
MAP_2_IGNORE_OPPONENTS_STATE = ['reward_machines/officeWorld/rm_m2_ignore_a1.txt', 'reward_machines/officeWorld/rm_m2_ignore_a2.txt']
MAP_3_RMS = ['reward_machines/officeWorld/reward_machines_m3_a1.txt', 'reward_machines/officeWorld/reward_machines_m3_a2.txt']